### ISSUE TITLE
How to fetch markets by a particular sport?

### ISSUE THREAD

**Issue by GitBolt** [MonacoProtocol/sdk#116]
I'm not sure if I could find about it in the documentaiton. But I want to be able to fetch all open markets for a particular sport, is there a list of all sports that are on the protocol? How do we fetch/filter them? Would appreciate a small code example in JS/TS.

Thanks!

**Comment by druspencer** [comment]
Hey @GitBolt I've moved your question over to discussions and answered it here https://github.com/MonacoProtocol/sdk/discussions/117 🙇 if you have any more questions, let me know. TLDR is: it's gonna be easier sooner 🤞
