### ISSUE TITLE
Fetching open markets but some markets throw error by saying they are locked

### ISSUE THREAD

**Issue by GitBolt** [MonacoProtocol/sdk#69]
Not sure why even tho I fetch open market events, for certain market orders, bets fail as they are locked. Not all markets have this issue, but some of the fetched ones do.
![image](https://user-images.githubusercontent.com/74103155/214586983-04fa62a1-a988-4b4c-a944-b528ff963af6.png)
This is my code:
```ts
const marketsStatus = MarketStatus.Open;

export const getMarkets = async (token: string, message: Message) => {
    const program = await getProgram(new PublicKey('monacoUXKtUi6vKsQwaLyxmXKSievfNWEcYXTgkbCih'));
    const marketsResponse: ClientResponse<MarketAccounts> =
        await getMarketAccountsByStatusAndMintAccount(
            program,
            marketsStatus,
            new PublicKey(token)
        );
# Other code
....
```
I thought this could be because when I execute the fetch request and when I make the order, the market must've locked in between, but when I fetch open markets again, I still get the same market back which was throwing locked issue.

**Comment by eoin-betdex** [comment]
Hey @GitBolt thanks for raising this issue. 

Without taking too deep a look I _think_ this is just down to a miss understanding, a small gap in functionality, and almost certainly a gap in documentation.

A market has both a [status](https://github.com/MonacoProtocol/protocol/blob/main/npm-client/types/market.ts#L6) as well as some other flags and attributes. 
```
export enum MarketStatus {
  Initializing = 0x00,
  Open = 0x01,
  Locked = 0x02,
  ReadyForSettlement = 0x03,
  Settled = 0x04,
  ReadyToClose = 0x05,
}
```

The `status` outlines the main lifecycle states a market can be in. `Locked` is indeed one of these states,
 however, as of right now it is not used. 

Market's also have a `marketLockTimestamp`, and [it is this field that is checked during order placement and raises the error you are getting](https://github.com/MonacoProtocol/protocol/blob/main/programs/monaco_protocol/src/instructions/order/create_order.rs#L116-L119).  

```
    require!(
        *market_lock_timestamp > now,
        CoreError::CreationMarketLocked
    );
```

So correctly or incorrectly, right now you can query for `Open` markets and receive a response containing markets where `marketLockTimestamp` is in the past. 

For now, if you want to avoid this, just filter out any markets that are already locked (based on this field)
```
openMarkets.filter(market => market.marketLockTimestamp.toNumber() > new Date())
```

We'll log the confusion around this as an issue against the protocol and see if it makes sense to have the market transition to the `Locked` state, or just remove that value from `MarketStatus` and rely purely on `marketLockTimestamp`.

**Comment by GitBolt** [comment]
Thanks a lot for the detailed explanation! Really appreciate it :)
